<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gabriele Sales, Elena Zuin, Sara Potente">

<title>RNA-seq pre-processing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hand-on-2_files/libs/clipboard/clipboard.min.js"></script>
<script src="hand-on-2_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="hand-on-2_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="hand-on-2_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="hand-on-2_files/libs/quarto-html/popper.min.js"></script>
<script src="hand-on-2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hand-on-2_files/libs/quarto-html/anchor.min.js"></script>
<link href="hand-on-2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hand-on-2_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hand-on-2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hand-on-2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hand-on-2_files/libs/bootstrap/bootstrap-f907e4f80467f7b6f79fe4ee3b9633f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">RNA-seq pre-processing</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gabriele Sales, Elena Zuin, Sara Potente </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this tutorial we’ll explore the exploratory gene expression analysis using Bioconductor packages.</p>
<section id="r-packages-installation" class="level2">
<h2 class="anchored" data-anchor-id="r-packages-installation">R packages installation</h2>
<p>We install R packages with the <em>install.packages</em> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"dplyr"</span>, <span class="st">"plyr"</span>, <span class="st">"corrplot"</span>, <span class="st">"ggfortify"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="bioconductor-installation" class="level2">
<h2 class="anchored" data-anchor-id="bioconductor-installation">Bioconductor installation</h2>
<p>Bioconductor is a free, open-source, and open-development software project. It is based primarily on the statistical programming language R and provides packages for the analysis and interpretation of high-throughput genomic data. For more information, see the <a href="https://www.bioconductor.org/">Bioconductor website</a>.</p>
<p>Installing Bioconductor requires the <strong>BiocManager</strong> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"BiocManager"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"BiocManager"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Last version of Bioconductor</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># BiocManager::install(version = "3.23")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="bioconductor-packages-installation" class="level3">
<h3 class="anchored" data-anchor-id="bioconductor-packages-installation">Bioconductor packages installation</h3>
<p>To install core packages, necessary for all practical lectures, we use the <code>install()</code> function of <strong>BiocManager</strong> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BiocManager::install(c("limma", "EDASeq", "edgeR"))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
</section>
<section id="load-packages" class="level1">
<h1>Load packages</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(limma)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EDASeq)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(edgeR)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(SummarizedExperiment)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="summarizedexperiment" class="level1">
<h1>SummarizedExperiment</h1>
<p>In this tutorial, we will use the lung adenocarcinoma (LUAD) dataset from The Cancer Genome Atlas (TCGA), a program that collects genomic mutations data from different types of tumors.</p>
<p>We will load the dataset previously saved in an RDS file.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>luad <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"/home/ilaria/Documents/GFC/esercitazioni/data/luad.rds"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>luad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: RangedSummarizedExperiment 
dim: 60660 539 
metadata(1): data_release
assays(2): raw_count normalized_count
rownames(60660): ENSG00000000003.15 ENSG00000000005.6 ...
  ENSG00000288674.1 ENSG00000288675.1
rowData names(10): source type ... hgnc_id havana_gene
colnames(539): TCGA-44-2665-01A-01R-0946-07
  TCGA-97-7937-01A-11R-2170-07 ... TCGA-97-7554-01A-11R-2039-07
  TCGA-97-8547-01A-11R-2403-07
colData names(93): barcode patient ... paper_Ploidy.ABSOLUTE.calls
  paper_Purity.ABSOLUTE.calls</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(luad)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RangedSummarizedExperiment"
attr(,"package")
[1] "SummarizedExperiment"</code></pre>
</div>
</div>
<p>The object luad is a RangedSummarizedExperiment, a specialized subclass of <strong>SummarizedExperiment</strong>. The main difference is that a RangedSummarizedExperiment object contains genomic positions associated with its rows.</p>
<p>The <strong>SummarizedExperiment</strong> class is a data structure commonly used in the analysis of biological data, such as genomic or transcriptomic datasets. It is designed to store experimental measurements (e.g., a count matrix) together with associated metadata describing the features and the samples.</p>
<p><img src="se.png" class="img-fluid"></p>
<p>A <strong>SummarizedExperiment</strong> object contains several components useful for storing and analyzing high-throughput genomic data:</p>
<ul>
<li><code>assays()</code> returns a list of gene expression matrices (e.g., raw and normalized counts). In the luad object, raw_count contains the raw count matrix with 60,606 genes (rows) and 539 samples (columns). For this tutorial, we will focus on raw_count and ignore the other matrix, normalized_count.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">assays</span>(luad)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of length 2
names(2): raw_count normalized_count</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To visualize the raw count matrix we can use assay() function</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(<span class="fu">assay</span>(luad, <span class="st">"raw_count"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "matrix" "array" </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We visualize the first six genes and the first six samples</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">assay</span>(luad, <span class="st">"raw_count"</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   TCGA-44-2665-01A-01R-0946-07 TCGA-97-7937-01A-11R-2170-07
ENSG00000000003.15                         4236                         4337
ENSG00000000005.6                          1321                            0
ENSG00000000419.13                         1799                         3201
ENSG00000000457.14                         1301                         1367
ENSG00000000460.17                          376                          625
ENSG00000000938.13                          823                          307
                   TCGA-44-2665-01B-06R-A277-07 TCGA-64-5774-01A-01R-1628-07
ENSG00000000003.15                          401                         4884
ENSG00000000005.6                            73                            0
ENSG00000000419.13                          154                         1736
ENSG00000000457.14                          221                          647
ENSG00000000460.17                          102                          543
ENSG00000000938.13                           79                          245
                   TCGA-78-7220-01A-11R-2039-07 TCGA-78-7155-01A-11R-2039-07
ENSG00000000003.15                         2906                         3875
ENSG00000000005.6                             0                            8
ENSG00000000419.13                         2724                         1171
ENSG00000000457.14                          909                          421
ENSG00000000460.17                          760                          814
ENSG00000000938.13                          286                          162</code></pre>
</div>
</div>
<ul>
<li><code>colnames()</code> returns a vector containing the sample names;</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(luad)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "TCGA-44-2665-01A-01R-0946-07" "TCGA-97-7937-01A-11R-2170-07"
[3] "TCGA-44-2665-01B-06R-A277-07" "TCGA-64-5774-01A-01R-1628-07"
[5] "TCGA-78-7220-01A-11R-2039-07" "TCGA-78-7155-01A-11R-2039-07"</code></pre>
</div>
</div>
<ul>
<li><code>colData()</code> returns information about the samples, e.g., sample name, survival, sex, age, and other attributes. These data are stored in a DataFrame object. Each row of the DataFrame corresponds to a sample (matching the columns of the SummarizedExperiment object), while each column represents a specific attribute of the samples;</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(<span class="fu">colData</span>(luad))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "DFrame"
attr(,"package")
[1] "S4Vectors"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colData</span>(luad)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 6 rows and 10 columns
                                            barcode      patient
                                        &lt;character&gt;  &lt;character&gt;
TCGA-44-2665-01A-01R-0946-07 TCGA-44-2665-01A-01R.. TCGA-44-2665
TCGA-97-7937-01A-11R-2170-07 TCGA-97-7937-01A-11R.. TCGA-97-7937
TCGA-44-2665-01B-06R-A277-07 TCGA-44-2665-01B-06R.. TCGA-44-2665
TCGA-64-5774-01A-01R-1628-07 TCGA-64-5774-01A-01R.. TCGA-64-5774
TCGA-78-7220-01A-11R-2039-07 TCGA-78-7220-01A-11R.. TCGA-78-7220
TCGA-78-7155-01A-11R-2039-07 TCGA-78-7155-01A-11R.. TCGA-78-7155
                                       sample shortLetterCode
                                  &lt;character&gt;     &lt;character&gt;
TCGA-44-2665-01A-01R-0946-07 TCGA-44-2665-01A              TP
TCGA-97-7937-01A-11R-2170-07 TCGA-97-7937-01A              TP
TCGA-44-2665-01B-06R-A277-07 TCGA-44-2665-01B              TP
TCGA-64-5774-01A-01R-1628-07 TCGA-64-5774-01A              TP
TCGA-78-7220-01A-11R-2039-07 TCGA-78-7220-01A              TP
TCGA-78-7155-01A-11R-2039-07 TCGA-78-7155-01A              TP
                                      definition sample_submitter_id
                                     &lt;character&gt;         &lt;character&gt;
TCGA-44-2665-01A-01R-0946-07 Primary solid Tumor    TCGA-44-2665-01A
TCGA-97-7937-01A-11R-2170-07 Primary solid Tumor    TCGA-97-7937-01A
TCGA-44-2665-01B-06R-A277-07 Primary solid Tumor    TCGA-44-2665-01B
TCGA-64-5774-01A-01R-1628-07 Primary solid Tumor    TCGA-64-5774-01A
TCGA-78-7220-01A-11R-2039-07 Primary solid Tumor    TCGA-78-7220-01A
TCGA-78-7155-01A-11R-2039-07 Primary solid Tumor    TCGA-78-7155-01A
                             sample_type_id tumor_descriptor
                                &lt;character&gt;      &lt;character&gt;
TCGA-44-2665-01A-01R-0946-07             01          Primary
TCGA-97-7937-01A-11R-2170-07             01          Primary
TCGA-44-2665-01B-06R-A277-07             01          Primary
TCGA-64-5774-01A-01R-1628-07             01          Primary
TCGA-78-7220-01A-11R-2039-07             01          Primary
TCGA-78-7155-01A-11R-2039-07             01          Primary
                                          sample_id   sample_type
                                        &lt;character&gt;   &lt;character&gt;
TCGA-44-2665-01A-01R-0946-07 a0863fa6-515c-44fa-8.. Primary Tumor
TCGA-97-7937-01A-11R-2170-07 cb0017ba-aee1-4046-8.. Primary Tumor
TCGA-44-2665-01B-06R-A277-07 9c146f5d-ca52-4cb9-a.. Primary Tumor
TCGA-64-5774-01A-01R-1628-07 252c5d60-7033-44c3-8.. Primary Tumor
TCGA-78-7220-01A-11R-2039-07 98038913-75d0-41a6-a.. Primary Tumor
TCGA-78-7155-01A-11R-2039-07 284de41b-6ad8-4c29-9.. Primary Tumor</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We use table() function to count living and deceased patients</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(luad<span class="sc">$</span>paper_Survival)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
DECEASED   LIVING 
      70      177 </code></pre>
</div>
</div>
<ul>
<li><code>rownames()</code> returns a vector of gene IDs, specifically Ensembl stable identifiers. The number after the dot (e.g., .15 in ENSG00000000003.15) indicates the version number of the gene annotation, which Ensembl increments each time the gene’s annotation is updated due to changes in genomic coordinates, transcript structure, or other refinements.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(luad)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ENSG00000000003.15" "ENSG00000000005.6"  "ENSG00000000419.13"
[4] "ENSG00000000457.14" "ENSG00000000460.17" "ENSG00000000938.13"</code></pre>
</div>
</div>
<ul>
<li><code>rowData()</code> and <code>rowRanges()</code> return information about the genes, such as gene or transcript IDs. These data are stored in a DataFrame object. Additionally, <code>rowRanges()</code> provides the chromosome and genomic coordinates for each gene.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(<span class="fu">rowData</span>(luad))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "DFrame"
attr(,"package")
[1] "S4Vectors"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowData</span>(luad)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 6 rows and 10 columns
                     source     type     score     phase            gene_id
                   &lt;factor&gt; &lt;factor&gt; &lt;numeric&gt; &lt;integer&gt;        &lt;character&gt;
ENSG00000000003.15   HAVANA     gene        NA        NA ENSG00000000003.15
ENSG00000000005.6    HAVANA     gene        NA        NA  ENSG00000000005.6
ENSG00000000419.13   HAVANA     gene        NA        NA ENSG00000000419.13
ENSG00000000457.14   HAVANA     gene        NA        NA ENSG00000000457.14
ENSG00000000460.17   HAVANA     gene        NA        NA ENSG00000000460.17
ENSG00000000938.13   HAVANA     gene        NA        NA ENSG00000000938.13
                        gene_type   gene_name       level     hgnc_id
                      &lt;character&gt; &lt;character&gt; &lt;character&gt; &lt;character&gt;
ENSG00000000003.15 protein_coding      TSPAN6           2  HGNC:11858
ENSG00000000005.6  protein_coding        TNMD           2  HGNC:17757
ENSG00000000419.13 protein_coding        DPM1           2   HGNC:3005
ENSG00000000457.14 protein_coding       SCYL3           2  HGNC:19285
ENSG00000000460.17 protein_coding    C1orf112           2  HGNC:25565
ENSG00000000938.13 protein_coding         FGR           2   HGNC:3697
                            havana_gene
                            &lt;character&gt;
ENSG00000000003.15 OTTHUMG00000022002.2
ENSG00000000005.6  OTTHUMG00000022001.2
ENSG00000000419.13 OTTHUMG00000032742.2
ENSG00000000457.14 OTTHUMG00000035941.6
ENSG00000000460.17 OTTHUMG00000035821.9
ENSG00000000938.13 OTTHUMG00000003516.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowRanges</span>(luad)[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GRanges object with 6 ranges and 10 metadata columns:
                     seqnames              ranges strand |   source     type
                        &lt;Rle&gt;           &lt;IRanges&gt;  &lt;Rle&gt; | &lt;factor&gt; &lt;factor&gt;
  ENSG00000000003.15     chrX 100627108-100639991      - |   HAVANA     gene
   ENSG00000000005.6     chrX 100584936-100599885      + |   HAVANA     gene
  ENSG00000000419.13    chr20   50934867-50958555      - |   HAVANA     gene
  ENSG00000000457.14     chr1 169849631-169894267      - |   HAVANA     gene
  ENSG00000000460.17     chr1 169662007-169854080      + |   HAVANA     gene
  ENSG00000000938.13     chr1   27612064-27635185      - |   HAVANA     gene
                         score     phase            gene_id      gene_type
                     &lt;numeric&gt; &lt;integer&gt;        &lt;character&gt;    &lt;character&gt;
  ENSG00000000003.15        NA      &lt;NA&gt; ENSG00000000003.15 protein_coding
   ENSG00000000005.6        NA      &lt;NA&gt;  ENSG00000000005.6 protein_coding
  ENSG00000000419.13        NA      &lt;NA&gt; ENSG00000000419.13 protein_coding
  ENSG00000000457.14        NA      &lt;NA&gt; ENSG00000000457.14 protein_coding
  ENSG00000000460.17        NA      &lt;NA&gt; ENSG00000000460.17 protein_coding
  ENSG00000000938.13        NA      &lt;NA&gt; ENSG00000000938.13 protein_coding
                       gene_name       level     hgnc_id          havana_gene
                     &lt;character&gt; &lt;character&gt; &lt;character&gt;          &lt;character&gt;
  ENSG00000000003.15      TSPAN6           2  HGNC:11858 OTTHUMG00000022002.2
   ENSG00000000005.6        TNMD           2  HGNC:17757 OTTHUMG00000022001.2
  ENSG00000000419.13        DPM1           2   HGNC:3005 OTTHUMG00000032742.2
  ENSG00000000457.14       SCYL3           2  HGNC:19285 OTTHUMG00000035941.6
  ENSG00000000460.17    C1orf112           2  HGNC:25565 OTTHUMG00000035821.9
  ENSG00000000938.13         FGR           2   HGNC:3697 OTTHUMG00000003516.3
  -------
  seqinfo: 25 sequences from an unspecified genome; no seqlengths</code></pre>
</div>
</div>
<ul>
<li><code>metadata()</code> contains other information</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metadata</span>(luad)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data_release
[1] "Data Release 42.0 - January 30, 2025"</code></pre>
</div>
</div>
<p>For a more detailed description see <a href="https://bioconductor.org/packages/release/bioc/vignettes/SummarizedExperiment/inst/doc/SummarizedExperiment.html">Bioconductor vignette</a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(luad) <span class="ot">&lt;-</span> <span class="fu">substr</span>(<span class="fu">rownames</span>(luad), <span class="dv">1</span>, <span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now, let’s visualize the patient cohort based on the clinical annotations coded by <em>paper_xxx</em> (clinical variable columns 74:93). To automatically create a data description table we use the <code>summary()</code> command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">colData</span>(luad)[, <span class="dv">74</span><span class="sc">:</span><span class="dv">93</span>]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">colData</span>(luad)[, <span class="fu">grepl</span>(<span class="st">"paper_"</span>, <span class="fu">colnames</span>(<span class="fu">colData</span>(luad)))]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">data.frame</span>(vars))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      paper_patient     paper_Sex       paper_Age.at.diagnosis paper_T.stage
 TCGA-44-2656:  3   FEMALE   :140   [Not Available]: 17        T2     :109  
 TCGA-44-2662:  3   MALE     :107   72             : 14        T1     : 36  
 TCGA-44-2665:  3   [unknown]:  1   70             : 13        T2a    : 29  
 TCGA-44-2666:  3   NAs      :291   65             : 12        T1b    : 19  
 TCGA-44-4112:  3                   59             : 11        T3     : 19  
 (Other)     :233                   (Other)        :181        (Other): 36  
 NAs         :291                   NAs            :291        NAs    :291  
         paper_N.stage  paper_Tumor.stage
 N0             :150   Stage IB  : 80    
 N1             : 45   Stage IA  : 52    
 N2             : 41   Stage IIIA: 38    
 N3             :  1   Stage IIB : 34    
 [Not Available]:  4   Stage IIA : 18    
 NX             :  7   (Other)   : 26    
 NAs            :291   NAs       :291    
                                  paper_Smoking.Status  paper_Survival
 Current reformed smoker for &gt; 15 years     : 79       DECEASED: 70   
 Current reformed smoker for &lt; or = 15 years: 77       LIVING  :177   
 Current smoker                             : 47       NAs     :292   
 Lifelong Non-smoker                        : 34                      
 [Not Available]                            : 11                      
 NAs                                        :291                      
                                                                      
 paper_Transversion.High.Low paper_Nonsilent.Mutations
 High:148                    Min.   :  13.00          
 Low :100                    1st Qu.:  76.25          
 NAs :291                    Median : 157.50          
                             Mean   : 237.69          
                             3rd Qu.: 289.50          
                             Max.   :1339.00          
                             NAs    :291              
 paper_Nonsilent.Mutations.per.Mb paper_Oncogene.Negative.or.Positive.Groups
 1,09   :  7                      Oncogene Negative: 91                     
 1,49   :  4                      Oncogene Positive:157                     
 1,95   :  4                      NAs              :291                     
 0,57   :  3                                                                
 11,02  :  3                                                                
 (Other):227                                                                
 NAs    :291                                                                
   paper_Fusions  paper_expression_subtype
          :237   prox.-inflam : 88        
 CLTC-ROS1:  3   prox.-prolif.: 63        
 EML4-ALK :  3   TRU          : 97        
 CCDC6-RET:  1   NAs          :291        
 CD74-ROS1:  1                            
 (Other)  :  3                            
 NAs      :291                            
 paper_chromosome.affected.by.chromothripsis paper_iCluster.Group
 chr1    :  2                                Min.   :1.000       
 chr19   :  1                                1st Qu.:3.000       
 chr20   :  1                                Median :4.000       
 chr3    :  1                                Mean   :3.802       
 multiple:  1                                3rd Qu.:5.000       
 NAs     :533                                Max.   :6.000       
                                             NAs    :291         
 paper_CIMP.methylation.signature.
 high         : 37                
 intermediate : 76                
 low          : 76                
 NAs          :350                
                                  
                                  
                                  
 paper_MTOR.mechanism.of.mTOR.pathway.activation paper_Ploidy.ABSOLUTE.calls
 Akt.pS473    : 47                               1,94   :  7                
 AMPK-LKB1_low: 20                               1,96   :  6                
 PI3K_mut     : 15                               2,12   :  6                
 STK11_mut    : 34                               1,86   :  5                
 unaligned    : 79                               3,39   :  5                
 NAs          :344                               (Other):219                
                                                 NAs    :291                
 paper_Purity.ABSOLUTE.calls
 0,42   : 10                
 0,25   :  9                
 0,35   :  9                
 0,44   :  9                
 0,59   :  9                
 (Other):202                
 NAs    :291                </code></pre>
</div>
</div>
<p>For an understanding of the clinical variables regarding lung cancer staging, look at <a href="https://www.ieo.it/it/PER-I-PAZIENTI/Cure/Tumori-al-polmone/">IEO website</a>, while for the other variables, refer to the original work published in <a href="https://www.nature.com/articles/nature13385">Nature in 2014</a> in particular to Figure 5 of the work.</p>
<p>The data description table is useful to check the presence of missing values (NAs) and the variables are interpreted correctly.</p>
<div class="blue">
<p><strong>Exercise 1</strong>: Compute the mean of the age at diagnosis (<code>paper_Age.at.diagnosis</code>)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Age at diagnosis is stored as a factor variable in the dataset.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(luad<span class="sc">$</span>paper_Age.at.diagnosis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(luad<span class="sc">$</span>paper_Age.at.diagnosis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mean.default(luad$paper_Age.at.diagnosis): argument is not numeric
or logical: returning NA</code></pre>
</div>
</div>
<p>The mean of age at diagnosis returns NA. So we have to convert this variable to a numeric vector.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>luad<span class="sc">$</span>paper_Age.at.diagnosis <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(luad<span class="sc">$</span>paper_Age.at.diagnosis)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(luad<span class="sc">$</span>paper_Age.at.diagnosis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We have to remove the NAs</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>mean_age <span class="ot">&lt;-</span> <span class="fu">mean</span>(luad<span class="sc">$</span>paper_Age.at.diagnosis, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<hr>
<section id="patients-selection" class="level2">
<h2 class="anchored" data-anchor-id="patients-selection">Patients selection</h2>
<p>For the next analysis we select the patients who have the smoking status different to a missing value.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>luad <span class="ot">&lt;-</span> luad[, <span class="sc">!</span><span class="fu">is.na</span>(luad<span class="sc">$</span>paper_Smoking.Status)]</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(luad<span class="sc">$</span>paper_Smoking.Status)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Current reformed smoker for &gt; 15 years 
                                         79 
Current reformed smoker for &lt; or = 15 years 
                                         77 
                             Current smoker 
                                         47 
                        Lifelong Non-smoker 
                                         34 
                            [Not Available] 
                                         11 </code></pre>
</div>
</div>
<p>Also we remove the patients with “Not Available” information.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>luad <span class="ot">&lt;-</span> luad[, luad<span class="sc">$</span>paper_Smoking.Status <span class="sc">!=</span> <span class="st">"[Not Available]"</span>]</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>luad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: RangedSummarizedExperiment 
dim: 60660 237 
metadata(1): data_release
assays(2): raw_count normalized_count
rownames(60660): ENSG00000000003 ENSG00000000005 ... ENSG00000288674
  ENSG00000288675
rowData names(10): source type ... hgnc_id havana_gene
colnames(237): TCGA-44-2665-01A-01R-0946-07
  TCGA-97-7937-01A-11R-2170-07 ... TCGA-55-6971-01A-11R-1949-07
  TCGA-97-7554-01A-11R-2039-07
colData names(93): barcode patient ... paper_Ploidy.ABSOLUTE.calls
  paper_Purity.ABSOLUTE.calls</code></pre>
</div>
</div>
<p>The dataset has been filtered and now contains 237 patients. Next, we identify genes that have all zero counts across all samples and remove them from the dataset. Maybe this filtering is not sufficient to remove all the low quality genes. We see this later</p>
<p>Next, we identify genes that have all zero counts across all samples and remove them from the dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># There are 3467 genes whose sum is equal to zero</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">rowSums</span>(<span class="fu">assay</span>(luad, <span class="st">"raw_count"</span>)) <span class="sc">==</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
57193  3467 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We keep the genes with the sum &gt; 0</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>luad <span class="ot">&lt;-</span> luad[<span class="fu">rowSums</span>(<span class="fu">assay</span>(luad, <span class="st">"raw_count"</span>)) <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>luad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: RangedSummarizedExperiment 
dim: 57193 237 
metadata(1): data_release
assays(2): raw_count normalized_count
rownames(57193): ENSG00000000003 ENSG00000000005 ... ENSG00000288674
  ENSG00000288675
rowData names(10): source type ... hgnc_id havana_gene
colnames(237): TCGA-44-2665-01A-01R-0946-07
  TCGA-97-7937-01A-11R-2170-07 ... TCGA-55-6971-01A-11R-1949-07
  TCGA-97-7554-01A-11R-2039-07
colData names(93): barcode patient ... paper_Ploidy.ABSOLUTE.calls
  paper_Purity.ABSOLUTE.calls</code></pre>
</div>
</div>
<p>This filtering step may not be sufficient to remove all low-quality genes, but we will fix this issue in the next tutorial.</p>
</section>
</section>
<section id="biological-question" class="level1">
<h1>Biological question</h1>
<p>The aim of our analysis is to identify the transcriptional differences between the three LUAD subtypes: terminal respiratory unit (TRU), proximal-inflammatory (prox.-inflam), and proximal-proliferative (prox.-prolif). The subtype information is stored in the <em>paper_expression_subtype</em> variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(luad<span class="sc">$</span>paper_expression_subtype)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 prox.-inflam prox.-prolif.           TRU 
           83            60            94 </code></pre>
</div>
</div>
</section>
<section id="exploratory-gene-expression-analysis" class="level1">
<h1>Exploratory gene expression analysis</h1>
<p>Every RNA-seq study begins with exploratory data analysis, where the data are visualized using boxplots, MD/MA plots, RLE plots, and Principal Component Analysis (PCA). These visualizations help answer key questions:</p>
<ul>
<li>Do different conditions or groups show distinct expression profiles?</li>
<li>Are there any outlier samples?</li>
</ul>
<section id="boxplot" class="level2">
<h2 class="anchored" data-anchor-id="boxplot">Boxplot</h2>
<p>We can start by visualizing the data using a boxplot. Before plotting, it is often necessary to transform the count matrix using a <code>log(counts + 1)</code> transformation. This transformation is important because:</p>
<ul>
<li>RNA-seq samples often have different sequencing depths. Log transformation stabilizes the variance and makes the distributions more comparable across samples;</li>
<li>most genes have low counts, and a few have very high counts. Log transformation makes the data more balanced and easier to analyze;</li>
<li>adding 1 in log(counts + 1) allows us to transform zero counts, which would otherwise be undefined;</li>
<li>improve interpretability.</li>
</ul>
<p>In R, we can apply this transformation using the <code>log1p()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>raw_count <span class="ot">&lt;-</span> <span class="fu">assay</span>(luad, <span class="st">"raw_count"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># For faster plotting, use only the first 20 samples</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(raw_count[, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-21-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To make readable the boxplot on all we reduce the string of column names.</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(raw_count) <span class="ot">&lt;-</span> <span class="fu">substr</span>(<span class="fu">colnames</span>(raw_count), <span class="dv">9</span>, <span class="dv">20</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log1p</span>(raw_count)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-21-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>col <span class="ot">&lt;-</span> luad<span class="sc">$</span>paper_expression_subtype</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(col)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "prox.-inflam"  "prox.-prolif." "TRU"          </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(col) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log1p</span>(raw_count)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>], <span class="at">col =</span> col, <span class="at">xlab =</span> <span class="st">"Sample"</span>, <span class="at">ylab =</span> <span class="st">"log1p expression"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>),  <span class="at">las =</span> <span class="dv">2</span>, <span class="at">cex.axis =</span> <span class="fl">0.7</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"top"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"prox.-inflam"</span>,<span class="st">"prox.-prolif."</span>, <span class="st">"TRU"</span>), <span class="at">col =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="fl">0.7</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-21-3.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<style>
  div.blue{background-color:#e6f0ff; border-radius: 4px; padding: 15px;}
  div.pink{background-color:#ffffcc; border-radius: 4px; padding: 15px;}
</style>
<hr>
<div class="blue">
<p><strong>Exercise 2</strong>: Recreate the boxplot using tidyverse and ggplot2</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>log1p <span class="ot">&lt;-</span> <span class="fu">log1p</span>((raw_count)[, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>])</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(log1p)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>gene <span class="ot">&lt;-</span> <span class="fu">rownames</span>(df)</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>df_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(df, <span class="at">cols =</span> <span class="sc">-</span>gene, <span class="at">names_to =</span> <span class="st">"Sample"</span>, <span class="at">values_to =</span> <span class="st">"Expression"</span>)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>subtype <span class="ot">&lt;-</span> <span class="fu">colData</span>(luad)<span class="sc">$</span>paper_expression_subtype[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(subtype) <span class="ot">&lt;-</span> <span class="fu">substr</span>(<span class="fu">colnames</span>(luad)[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>], <span class="dv">9</span>, <span class="dv">20</span>)</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>df_long<span class="sc">$</span>Subtype <span class="ot">&lt;-</span> subtype[df_long<span class="sc">$</span>Sample]</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot with ggplot2</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_long, <span class="fu">aes</span>(<span class="at">x =</span> Sample, <span class="at">y =</span> Expression, <span class="at">fill =</span> Subtype)) <span class="sc">+</span></span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.color =</span> <span class="st">"black"</span>, <span class="at">outlier.shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"prox.-inflam"</span> <span class="ot">=</span> <span class="st">"black"</span>, <span class="st">"prox.-prolif."</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"TRU"</span> <span class="ot">=</span> <span class="st">"green"</span>)) <span class="sc">+</span></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sample"</span>,</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"log1p(Expression)"</span>,</span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Subtype"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-22-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</div>
<hr>
</section>
<section id="md-or-ma-charts" class="level2">
<h2 class="anchored" data-anchor-id="md-or-ma-charts">MD or MA charts</h2>
<p>In addition to the boxplot we can use the MA or MD charts.</p>
<p>To visualize the MA plot we can use the <code>plotMA()</code> function of <strong>limma</strong> package.</p>
<p>An MA plot visualizes differential expression results by plotting log2 fold change (M = log2(sample/virtual sample)) on the y-axis against mean normalized expression (A = average log counts) on the x-axis.</p>
<p>Most points should cluster around the horizontal line at M=0 (no change). Trends or biases away from this line indicate normalization issues or intensity-dependent effects. Outliers with large |M| values (&gt;2) highlight highly differentially expressed genes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>limma<span class="sc">::</span><span class="fu">plotMA</span>(<span class="fu">log1p</span>(raw_count), <span class="at">main =</span> <span class="st">""</span>, <span class="at">xlab =</span> <span class="st">"A"</span>, <span class="at">ylab =</span> <span class="st">"M"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-23-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>While, to visualize the MD plot we can use the <code>MDplot()</code> function of the <strong>EDASeq</strong> package. In particular, we choose a pair of experiments for comparison (6 and 7 samples). In this case, we use the raw count matrix.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MDPlot</span>(raw_count, <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">7</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-24-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">MDPlot</span>(raw_count, <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">6</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-24-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="rle-plot" class="level2">
<h2 class="anchored" data-anchor-id="rle-plot">RLE plot</h2>
<p>Next, we visualize the data using an RLE (Relative Log Expression) plot before normalization, using the <code>plotRLE()</code> function from the <strong>EDASeq</strong> package.</p>
<p>RLE plots are useful to check the differences between samples. Ideally, the median of boxplot should be centered around zero. Deviations indicate technical variation or differences in library size that may need normalization.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotRLE</span>(raw_count, <span class="at">outline =</span> <span class="cn">FALSE</span>, <span class="at">las =</span> <span class="dv">2</span>,</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"RLE"</span>, <span class="at">main =</span> <span class="st">"RLE of raw counts"</span>, <span class="at">col =</span> col)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-25-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>As expected the <strong>RLE</strong> graphs are very heterogeneous. In the next lession we will check how they change after normalization.</p>
</section>
<section id="principal-component-analysis" class="level2">
<h2 class="anchored" data-anchor-id="principal-component-analysis">Principal Component Analysis</h2>
<p>Principal component analysis (PCA) is used to project a high-dimensional dataset (where the number of dimensions equals the number of genes or transcripts) onto few dimensions. In R, PCA can be computed using the built-in <code>prcomp()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(<span class="fu">t</span>(<span class="fu">log1p</span>(raw_count)))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pca)<span class="sc">$</span>importance[, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            PC1      PC2      PC3      PC4      PC5      PC6
Standard deviation     74.64299 69.76526 36.85177 34.61316 30.07878 29.36374
Proportion of Variance  0.16064  0.14033  0.03915  0.03454  0.02608  0.02486
Cumulative Proportion   0.16064  0.30097  0.34012  0.37466  0.40075  0.42561
                            PC7      PC8      PC9     PC10     PC11     PC12
Standard deviation     26.26843 25.36954 24.13573 22.05843 21.11264 20.32502
Proportion of Variance  0.01989  0.01856  0.01680  0.01403  0.01285  0.01191
Cumulative Proportion   0.44550  0.46406  0.48085  0.49488  0.50773  0.51964
                           PC13     PC14     PC15     PC16     PC17     PC18
Standard deviation     19.09950 18.48902 17.87242 16.90135 16.62487 16.24443
Proportion of Variance  0.01052  0.00986  0.00921  0.00824  0.00797  0.00761
Cumulative Proportion   0.53016  0.54002  0.54923  0.55746  0.56543  0.57304
                           PC19     PC20
Standard deviation     15.90422 15.65503
Proportion of Variance  0.00729  0.00707
Cumulative Proportion   0.58033  0.58740</code></pre>
</div>
</div>
<p>The proportion of variance explains how much of the variation in a dataset can be attributed to a specific component. For example, the proportion variance attributes to the first component is equal to 0.16.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pca)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-27-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The Principal Component matrix has the same dimensions as the original data matrix; however, many of the PCs may not be informative, so a reduction in the number of PCs is typically required. To do so, it is useful to examine the amount of variance explained by each new PC vector, using the scree plot criterion. The number of components to be chosen corresponds variance drops dramatically in size.</p>
<p>In this case we choose the first two components.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">screeplot</span>(pca, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"lines"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-28-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="filtering" class="level1">
<h1>Filtering (?)</h1>
<p>In the previous part of the lesson, genes with all zero counts were removed. However, this is not sufficient because it does not eliminate genes with very low counts. We decided to keep only the genes with raw counts <span class="math inline">\(\geq 10\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>luad_sel <span class="ot">&lt;-</span> luad[<span class="fu">rowSums</span>(<span class="fu">assay</span>(luad, <span class="st">"raw_count"</span>)) <span class="sc">&gt;=</span> <span class="dv">10</span>, ]</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>luad_sel</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: RangedSummarizedExperiment 
dim: 52215 237 
metadata(1): data_release
assays(2): raw_count normalized_count
rownames(52215): ENSG00000000003 ENSG00000000005 ... ENSG00000288674
  ENSG00000288675
rowData names(10): source type ... hgnc_id havana_gene
colnames(237): TCGA-44-2665-01A-01R-0946-07
  TCGA-97-7937-01A-11R-2170-07 ... TCGA-55-6971-01A-11R-1949-07
  TCGA-97-7554-01A-11R-2039-07
colData names(93): barcode patient ... paper_Ploidy.ABSOLUTE.calls
  paper_Purity.ABSOLUTE.calls</code></pre>
</div>
</div>
</section>
<section id="normalization" class="level1">
<h1>Normalization</h1>
<p>Normalization of RNA-seq read counts is an essential procedure that corrects for non-biological variation of samples due to library preparation, sequencing read depth, gene length, mapping bias and other technical issues. Normalization is composed of two main steps: within-sample normalization and between-sample normalization.</p>
<section id="within-samples-normalization" class="level2">
<h2 class="anchored" data-anchor-id="within-samples-normalization">Within samples normalization</h2>
<p>The within-samples normalization is necessary for GC-content bias.</p>
<p>come giustifichiamo che non gliela facciamo vedere? mettiamo un png che mostra la differenza tra le due?</p>
<p>e diciamo che in questi dati non ne abbiamo bisogno + reference link per farla</p>
</section>
<section id="between-samples-normalization" class="level2">
<h2 class="anchored" data-anchor-id="between-samples-normalization">Between samples normalization</h2>
<p>After the within normalization we can compute the between normalization, using an R packages: <strong>edgeR</strong>.</p>
<p>We can utilize the <code>calcNormFactors</code> and <code>cpm</code> functions to estimate the normalizing factors for <code>RLE</code>, <code>TMM</code>, <code>upper quartile</code>, and <code>total count</code> normalizations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>raw_count <span class="ot">&lt;-</span> <span class="fu">assay</span>(luad_sel, <span class="st">"raw_count"</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>lbs <span class="ot">&lt;-</span> <span class="fu">calcNormFactors</span>(raw_count, <span class="at">method =</span> <span class="st">"RLE"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>calcNormFactors has been renamed to normLibSizes</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>rle <span class="ot">&lt;-</span> <span class="fu">cpm</span>(raw_count, <span class="at">lib.size =</span> lbs <span class="sc">*</span> <span class="fu">colSums</span>(raw_count))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>lbs <span class="ot">&lt;-</span> <span class="fu">calcNormFactors</span>(raw_count, <span class="at">method =</span> <span class="st">"TMM"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>calcNormFactors has been renamed to normLibSizes</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>tmm <span class="ot">&lt;-</span> <span class="fu">cpm</span>(raw_count, <span class="at">lib.size =</span> lbs <span class="sc">*</span> <span class="fu">colSums</span>(raw_count))</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>lbs <span class="ot">&lt;-</span> <span class="fu">calcNormFactors</span>(raw_count, <span class="at">method =</span> <span class="st">"upperquartile"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>calcNormFactors has been renamed to normLibSizes</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>uq <span class="ot">&lt;-</span> <span class="fu">cpm</span>(raw_count, <span class="at">lib.size =</span> lbs <span class="sc">*</span> <span class="fu">colSums</span>(raw_count))</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>tc <span class="ot">&lt;-</span> <span class="fu">cpm</span>(raw_count)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="boxplot-1" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-1">Boxplot</h3>
<p>Expression matrix visualization after normalization using boxplot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log2</span>(raw_count <span class="sc">+</span> <span class="dv">1</span>), <span class="at">outline =</span> <span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"log(count+1)"</span>, <span class="at">main =</span> <span class="st">"Before normalization"</span>, <span class="at">xaxt =</span> <span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-31-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log2</span>(tc <span class="sc">+</span> <span class="dv">1</span>), <span class="at">outline =</span> <span class="cn">FALSE</span>, <span class="at">las =</span> <span class="dv">2</span>,</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"log(count+1)"</span>, <span class="at">main =</span> <span class="st">"Boxplot Total count"</span>, <span class="at">xaxt=</span><span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-31-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log2</span>(rle <span class="sc">+</span> <span class="dv">1</span>), <span class="at">outline=</span><span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>,</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"log(count+1)"</span>, <span class="at">main =</span> <span class="st">"Boxplot RLE"</span>, <span class="at">xaxt =</span> <span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-31-3.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log2</span>(tmm <span class="sc">+</span> <span class="dv">1</span>), <span class="at">outline=</span><span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>,</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"log(count+1)"</span>, <span class="at">main =</span> <span class="st">"Boxplot TMM"</span>, <span class="at">xaxt =</span> <span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-31-4.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log2</span>(uq <span class="sc">+</span> <span class="dv">1</span>), <span class="at">outline=</span><span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>,</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"log(count+1)"</span>, <span class="at">main =</span> <span class="st">"Boxplot Upper quartile"</span>, <span class="at">xaxt =</span> <span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-31-5.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="rle-plot-1" class="level3">
<h3 class="anchored" data-anchor-id="rle-plot-1">RLE plot</h3>
<p>Expression matrix visualization after normalization using RLE plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>col <span class="ot">&lt;-</span> luad<span class="sc">$</span>paper_expression_subtype</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(col) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotRLE</span>(raw_count, <span class="at">outline =</span> <span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>, <span class="at">col=</span>col,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"RLE"</span>, <span class="at">main =</span> <span class="st">"RLE before normalization"</span>, <span class="at">xaxt=</span><span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-32-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotRLE</span>(tc, <span class="at">outline =</span> <span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>, <span class="at">col=</span>col,</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"RLE"</span>, <span class="at">main =</span> <span class="st">"RLE total count"</span>, <span class="at">xaxt=</span><span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-32-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotRLE</span>(tmm, <span class="at">outline =</span> <span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>, <span class="at">col=</span>col,</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"RLE"</span>, <span class="at">main =</span> <span class="st">"RLE TMM"</span>, <span class="at">xaxt=</span><span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-32-3.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotRLE</span>(rle, <span class="at">outline =</span> <span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>, <span class="at">col=</span>col,</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"RLE"</span>, <span class="at">main =</span> <span class="st">"RLE RLE"</span>, <span class="at">xaxt=</span><span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-32-4.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotRLE</span>(uq, <span class="at">outline =</span> <span class="cn">FALSE</span>,  <span class="at">las=</span><span class="dv">2</span>, <span class="at">col=</span>col,</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"RLE"</span>, <span class="at">main =</span> <span class="st">"RLE upper quartile"</span>, <span class="at">xaxt=</span><span class="st">'n'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-32-5.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="principal-component-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="principal-component-analysis-1">Principal component analysis</h3>
<p>PCA analysis in the context of normalization performance assessment is useful only if an <em>a priori</em> biological information on sample stratification is available. It is reasonable to select the normalization that better recognize the known stratification.</p>
<p>Now let’s see the basic functions of R to make <em>PCA</em> and then we will use the data normalized with the <em>TMM</em> to explore the results. Finally we will use the <em>plotPCA</em> function to plot scores across all the normalizations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>luad_pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(<span class="fu">t</span>(<span class="fu">log1p</span>(tmm)))</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">summary</span>(luad_pca)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>tmp<span class="sc">$</span>importance[, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            PC1      PC2      PC3      PC4      PC5      PC6
Standard deviation     35.24617 22.55519 21.91885 18.05110 17.48964 16.16087
Proportion of Variance  0.16095  0.06591  0.06224  0.04222  0.03963  0.03384
Cumulative Proportion   0.16095  0.22686  0.28910  0.33132  0.37095  0.40478
                            PC7      PC8      PC9     PC10     PC11     PC12
Standard deviation     14.31932 13.36711 12.80892 12.18753 10.71250 10.51829
Proportion of Variance  0.02656  0.02315  0.02126  0.01924  0.01487  0.01433
Cumulative Proportion   0.43135  0.45450  0.47575  0.49500  0.50986  0.52420
                           PC13     PC14     PC15     PC16     PC17     PC18
Standard deviation     10.20947 9.695005 9.448997 9.222683 8.555611 8.404443
Proportion of Variance  0.01350 0.012180 0.011570 0.011020 0.009480 0.009150
Cumulative Proportion   0.53770 0.549880 0.561450 0.572470 0.581950 0.591100
                           PC19     PC20
Standard deviation     8.021178 7.872259
Proportion of Variance 0.008340 0.008030
Cumulative Proportion  0.599440 0.607470</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(luad_pca)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-33-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">screeplot</span>(luad_pca, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"lines"</span>))  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-33-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Now we use the <em>plotPCA</em>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotPCA</span>(tc, <span class="at">k=</span><span class="dv">3</span>, <span class="at">labels=</span>F, <span class="at">col=</span><span class="fu">as.numeric</span>(col), <span class="at">pch=</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-34-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotPCA</span>(tmm, <span class="at">k=</span><span class="dv">3</span>, <span class="at">labels=</span>F, <span class="at">col=</span><span class="fu">as.numeric</span>(col), <span class="at">pch=</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-34-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>EDASeq<span class="sc">::</span><span class="fu">plotPCA</span>(rle, <span class="at">k=</span><span class="dv">3</span>, <span class="at">labels=</span>F, <span class="at">col=</span><span class="fu">as.numeric</span>(col), <span class="at">pch=</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fig/preprocessing-unnamed-chunk-34-3.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="save-the-data-for-the-next-tutorial" class="level1">
<h1>Save the data for the next tutorial</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(<span class="at">list =</span> <span class="fu">c</span>(<span class="st">"luad_sel"</span>, <span class="st">"luad"</span>, <span class="st">"tmm"</span>, <span class="st">"rle"</span>, <span class="st">"tc"</span>, <span class="st">"raw_count"</span>), <span class="at">file =</span> <span class="st">"normalization.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>